name: Worker

on:
  schedule:
  - cron: "*/5 * * * *"
  issues:
    types: [opened, closed, reopened]

jobs:
  update_myself:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set timezone
        run: sudo timedatectl set-timezone Europe/Moscow

      - name: Update README localy
        run: make update

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md last_run.md
          git commit -m "Auto run ${{ github.run_number }}" || echo "Nothing changed"
        if: success()

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: success()
